plugins: [jekyll-paginate]
highlighter: rouge
paginate: 3
markdown: kramdown
kramdown:
   math_engine: katex


permalink: "/:year/:month/:day/:title.html"

title: "Wishful Coding"
tagline: "Didn't you ever wish your computer understood you?"
url: "http://pepijndevos.nl"

gems:
  - jekyll-paginate
  - jekyll-feed
