highlighter: rouge
paginate: 3
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
incremental: true

permalink: "/:year/:month/:day/:title.html"

title: "Wishful Coding"
tagline: "Didn't you ever wish your<br>computer understood you?"
url: "http://pepijndevos.nl"

lsi: true

jekyll-archives:
  enabled:
    - categories
    - year